package models

import (
	"fmt"
	"time"

	g "github.com/matoous/go-nanoid/v2"
	"gorm.io/gorm"
)

type Emplx1 struct {
	FCADDAPVBY string    `gorm:"column:FCADDAPVBY;" json:"fcaddapvby"  form:"fcaddapvby" `
	FCAMPHUR   string    `gorm:"column:FCAMPHUR;" json:"fcamphur"  form:"fcamphur" `
	FCAMPHUR2  string    `gorm:"column:FCAMPHUR2;" json:"fcamphur2"  form:"fcamphur2" `
	FCAPPLCODE string    `gorm:"column:FCAPPLCODE;" json:"fcapplcode"  form:"fcapplcode" `
	FCAPPNAME  string    `gorm:"column:FCAPPNAME;" json:"fcappname"  form:"fcappname" `
	FCBBRANCH  string    `gorm:"column:FCBBRANCH;" json:"fcbbranch"  form:"fcbbranch" `
	FCBIRTPROV string    `gorm:"column:FCBIRTPROV;" json:"fcbirtprov"  form:"fcbirtprov" `
	FCBLOOD    string    `gorm:"column:FCBLOOD;" json:"fcblood"  form:"fcblood" `
	FCBOICARD  string    `gorm:"column:FCBOICARD;" json:"fcboicard"  form:"fcboicard" `
	FCBRANCH   string    `gorm:"column:FCBRANCH;" json:"fcbranch"  form:"fcbranch" `
	FCBUILDIN2 string    `gorm:"column:FCBUILDIN2;" json:"fcbuildin2"  form:"fcbuildin2" `
	FCBUILDING string    `gorm:"column:FCBUILDING;" json:"fcbuilding"  form:"fcbuilding" `
	FCCALFUND  string    `gorm:"column:FCCALFUND;" json:"fccalfund"  form:"fccalfund" `
	FCCALOT    string    `gorm:"column:FCCALOT;" json:"fccalot"  form:"fccalot" `
	FCCALSOC   string    `gorm:"column:FCCALSOC;" json:"fccalsoc"  form:"fccalsoc" `
	FCCALTMETH string    `gorm:"column:FCCALTMETH;" json:"fccaltmeth"  form:"fccaltmeth" `
	FCCFATHID  string    `gorm:"column:FCCFATHID;" json:"fccfathid"  form:"fccfathid" `
	FCCMOTHID  string    `gorm:"column:FCCMOTHID;" json:"fccmothid"  form:"fccmothid" `
	FCCODE     string    `gorm:"column:FCCODE;" json:"fccode"  form:"fccode" `
	FCCODE2    string    `gorm:"column:FCCODE2;" json:"fccode2"  form:"fccode2" `
	FCCOOPNO   string    `gorm:"column:FCCOOPNO;" json:"fccoopno"  form:"fccoopno" `
	FCCORP     string    `gorm:"column:FCCORP;" json:"fccorp"  form:"fccorp" `
	FCCORRECTB string    `gorm:"column:FCCORRECTB;" json:"fccorrectb"  form:"fccorrectb" `
	FCCOUPCALC string    `gorm:"column:FCCOUPCALC;" json:"fccoupcalc"  form:"fccoupcalc" `
	FCCOUPNAME string    `gorm:"column:FCCOUPNAME;" json:"fccoupname"  form:"fccoupname" `
	FCCREATEAP string    `gorm:"column:FCCREATEAP;" json:"fccreateap"  form:"fccreateap" `
	FCCREATEBY string    `gorm:"column:FCCREATEBY;" json:"fccreateby"  form:"fccreateby" `
	FCCTPERSON string    `gorm:"column:FCCTPERSON;" json:"fcctperson"  form:"fcctperson" `
	FCCTTEL    string    `gorm:"column:FCCTTEL;" json:"fccttel"  form:"fccttel" `
	FCCUACC    string    `gorm:"column:FCCUACC;" json:"fccuacc"  form:"fccuacc" `
	FCDATAIMP  string    `gorm:"column:FCDATAIMP;" json:"fcdataimp"  form:"fcdataimp" `
	FCDATASER  string    `gorm:"column:FCDATASER;" json:"fcdataser"  form:"fcdataser" `
	FCDELAPVBY string    `gorm:"column:FCDELAPVBY;" json:"fcdelapvby"  form:"fcdelapvby" `
	FCDRIVEID1 string    `gorm:"column:FCDRIVEID1;" json:"fcdriveid1"  form:"fcdriveid1" `
	FCDRIVEID2 string    `gorm:"column:FCDRIVEID2;" json:"fcdriveid2"  form:"fcdriveid2" `
	FCDRIVETY1 string    `gorm:"column:FCDRIVETY1;" json:"fcdrivety1"  form:"fcdrivety1" `
	FCDRIVETY2 string    `gorm:"column:FCDRIVETY2;" json:"fcdrivety2"  form:"fcdrivety2" `
	FCDTYPE1   string    `gorm:"column:FCDTYPE1;" json:"fcdtype1"  form:"fcdtype1" `
	FCDTYPE2   string    `gorm:"column:FCDTYPE2;" json:"fcdtype2"  form:"fcdtype2" `
	FCDTYPE3   string    `gorm:"column:FCDTYPE3;" json:"fcdtype3"  form:"fcdtype3" `
	FCDTYPE4   string    `gorm:"column:FCDTYPE4;" json:"fcdtype4"  form:"fcdtype4" `
	FCDTYPE5   string    `gorm:"column:FCDTYPE5;" json:"fcdtype5"  form:"fcdtype5" `
	FCDTYPE6   string    `gorm:"column:FCDTYPE6;" json:"fcdtype6"  form:"fcdtype6" `
	FCDTYPE7   string    `gorm:"column:FCDTYPE7;" json:"fcdtype7"  form:"fcdtype7" `
	FCDTYPE8   string    `gorm:"column:FCDTYPE8;" json:"fcdtype8"  form:"fcdtype8" `
	FCDTYPE9   string    `gorm:"column:FCDTYPE9;" json:"fcdtype9"  form:"fcdtype9" `
	FCEAFTERR  string    `gorm:"column:FCEAFTERR;" json:"fceafterr"  form:"fceafterr" `
	FCEDTAPVBY string    `gorm:"column:FCEDTAPVBY;" json:"fcedtapvby"  form:"fcedtapvby" `
	FCEMAIL    string    `gorm:"column:FCEMAIL;" json:"fcemail"  form:"fcemail" `
	FCEMPL     string    `gorm:"column:FCEMPL;" json:"fcempl"  form:"fcempl" `
	FCEMPLFIX  string    `gorm:"column:FCEMPLFIX;" json:"fcemplfix"  form:"fcemplfix" `
	FCEMPLGRP  string    `gorm:"column:FCEMPLGRP;" json:"fcemplgrp"  form:"fcemplgrp" `
	FCEMPLTYPE string    `gorm:"column:FCEMPLTYPE;" json:"fcempltype"  form:"fcempltype" `
	FCFATHID   string    `gorm:"column:FCFATHID;" json:"fcfathid"  form:"fcfathid" `
	FCFAX      string    `gorm:"column:FCFAX;" json:"fcfax"  form:"fcfax" `
	FCFCHR     string    `gorm:"column:FCFCHR;" json:"fcfchr"  form:"fcfchr" `
	FCFLOOR    string    `gorm:"column:FCFLOOR;" json:"fcfloor"  form:"fcfloor" `
	FCFLOOR2   string    `gorm:"column:FCFLOOR2;" json:"fcfloor2"  form:"fcfloor2" `
	FCFOREIGID string    `gorm:"column:FCFOREIGID;" json:"fcforeigid"  form:"fcforeigid" `
	FCFUNDNO   string    `gorm:"column:FCFUNDNO;" json:"fcfundno"  form:"fcfundno" `
	FCGID      string    `gorm:"column:FCGID;" json:"fcgid"  form:"fcgid" `
	FCHOSPITAL string    `gorm:"column:FCHOSPITAL;" json:"fchospital"  form:"fchospital" `
	FCID       string    `gorm:"column:FCID;" json:"fcid"  form:"fcid" `
	FCIDDIST   string    `gorm:"column:FCIDDIST;" json:"fciddist"  form:"fciddist" `
	FCIDPROV   string    `gorm:"column:FCIDPROV;" json:"fcidprov"  form:"fcidprov" `
	FCIM01     string    `gorm:"column:FCIM01;" json:"fcim01"  form:"fcim01" `
	FCIM02     string    `gorm:"column:FCIM02;" json:"fcim02"  form:"fcim02" `
	FCIM03     string    `gorm:"column:FCIM03;" json:"fcim03"  form:"fcim03" `
	FCISCFATCA string    `gorm:"column:FCISCFATCA;" json:"fciscfatca"  form:"fciscfatca" `
	FCISCMOTCA string    `gorm:"column:FCISCMOTCA;" json:"fciscmotca"  form:"fciscmotca" `
	FCISFATCAL string    `gorm:"column:FCISFATCAL;" json:"fcisfatcal"  form:"fcisfatcal" `
	FCISMOTCAL string    `gorm:"column:FCISMOTCAL;" json:"fcismotcal"  form:"fcismotcal" `
	FCISUSED   string    `gorm:"column:FCISUSED;" json:"fcisused"  form:"fcisused" `
	FCJOB      string    `gorm:"column:FCJOB;" json:"fcjob"  form:"fcjob" `
	FCLID      string    `gorm:"column:FCLID;" json:"fclid"  form:"fclid" `
	FCMANFLAG  string    `gorm:"column:FCMANFLAG;" json:"fcmanflag"  form:"fcmanflag" `
	FCMARYDIST string    `gorm:"column:FCMARYDIST;" json:"fcmarydist"  form:"fcmarydist" `
	FCMARYPROV string    `gorm:"column:FCMARYPROV;" json:"fcmaryprov"  form:"fcmaryprov" `
	FCMARYSTAT string    `gorm:"column:FCMARYSTAT;" json:"fcmarystat"  form:"fcmarystat" `
	FCMARYYEAR string    `gorm:"column:FCMARYYEAR;" json:"fcmaryyear"  form:"fcmaryyear" `
	FCMILITST  string    `gorm:"column:FCMILITST;" json:"fcmilitst"  form:"fcmilitst" `
	FCMOBILE   string    `gorm:"column:FCMOBILE;" json:"fcmobile"  form:"fcmobile" `
	FCMOO      string    `gorm:"column:FCMOO;" json:"fcmoo"  form:"fcmoo" `
	FCMOO2     string    `gorm:"column:FCMOO2;" json:"fcmoo2"  form:"fcmoo2" `
	FCMOTHID   string    `gorm:"column:FCMOTHID;" json:"fcmothid"  form:"fcmothid" `
	FCNAME     string    `gorm:"column:FCNAME;" json:"fcname"  form:"fcname" `
	FCNAME2    string    `gorm:"column:FCNAME2;" json:"fcname2"  form:"fcname2" `
	FCNATION   string    `gorm:"column:FCNATION;" json:"fcnation"  form:"fcnation" `
	FCNICKNAME string    `gorm:"column:FCNICKNAME;" json:"fcnickname"  form:"fcnickname" `
	FCNO       string    `gorm:"column:FCNO;" json:"fcno"  form:"fcno" `
	FCNO2      string    `gorm:"column:FCNO2;" json:"fcno2"  form:"fcno2" `
	FCORGCODE  string    `gorm:"column:FCORGCODE;" json:"fcorgcode"  form:"fcorgcode" `
	FCPASSPORT string    `gorm:"column:FCPASSPORT;" json:"fcpassport"  form:"fcpassport" `
	FCPAYBY    string    `gorm:"column:FCPAYBY;" json:"fcpayby"  form:"fcpayby" `
	FCPRBANK   string    `gorm:"column:FCPRBANK;" json:"fcprbank"  form:"fcprbank" `
	FCPRENAME  string    `gorm:"column:FCPRENAME;" json:"fcprename"  form:"fcprename" `
	FCPRENAME2 string    `gorm:"column:FCPRENAME2;" json:"fcprename2"  form:"fcprename2" `
	FCPROVINC2 string    `gorm:"column:FCPROVINC2;" json:"fcprovinc2"  form:"fcprovinc2" `
	FCPROVINCE string    `gorm:"column:FCPROVINCE;" json:"fcprovince"  form:"fcprovince" `
	FCPRPAYTYP string    `gorm:"column:FCPRPAYTYP;" json:"fcprpaytyp"  form:"fcprpaytyp" `
	FCQCBANKAC string    `gorm:"column:FCQCBANKAC;" json:"fcqcbankac"  form:"fcqcbankac" `
	FCQUITWHY  string    `gorm:"column:FCQUITWHY;" json:"fcquitwhy"  form:"fcquitwhy" `
	FCRACE     string    `gorm:"column:FCRACE;" json:"fcrace"  form:"fcrace" `
	FCREGION   string    `gorm:"column:FCREGION;" json:"fcregion"  form:"fcregion" `
	FCRFPERSON string    `gorm:"column:FCRFPERSON;" json:"fcrfperson"  form:"fcrfperson" `
	FCRFTEL    string    `gorm:"column:FCRFTEL;" json:"fcrftel"  form:"fcrftel" `
	FCROAD     string    `gorm:"column:FCROAD;" json:"fcroad"  form:"fcroad" `
	FCROAD2    string    `gorm:"column:FCROAD2;" json:"fcroad2"  form:"fcroad2" `
	FCROOMNO   string    `gorm:"column:FCROOMNO;" json:"fcroomno"  form:"fcroomno" `
	FCROOMNO2  string    `gorm:"column:FCROOMNO2;" json:"fcroomno2"  form:"fcroomno2" `
	FCSECT     string    `gorm:"column:FCSECT;" json:"fcsect"  form:"fcsect" `
	FCSELTAG   string    `gorm:"column:FCSELTAG;" json:"fcseltag"  form:"fcseltag" `
	FCSEX      string    `gorm:"column:FCSEX;" json:"fcsex"  form:"fcsex" `
	FCSKID     string    `gorm:"primaryKey;column:FCSKID;size:8;unique;index;" json:"fcskid"  form:"fcskid" `
	FCSOCID    string    `gorm:"column:FCSOCID;" json:"fcsocid"  form:"fcsocid" `
	FCSOI      string    `gorm:"column:FCSOI;" json:"fcsoi"  form:"fcsoi" `
	FCSOI2     string    `gorm:"column:FCSOI2;" json:"fcsoi2"  form:"fcsoi2" `
	FCSRCUPD   string    `gorm:"column:FCSRCUPD;" json:"fcsrcupd"  form:"fcsrcupd" `
	FCSTAT     string    `gorm:"column:FCSTAT;" json:"fcstat"  form:"fcstat" `
	FCTAMBON   string    `gorm:"column:FCTAMBON;" json:"fctambon"  form:"fctambon" `
	FCTAMBON2  string    `gorm:"column:FCTAMBON2;" json:"fctambon2"  form:"fctambon2" `
	FCTAXID    string    `gorm:"column:FCTAXID;" json:"fctaxid"  form:"fctaxid" `
	FCTEL      string    `gorm:"column:FCTEL;" json:"fctel"  form:"fctel" `
	FCTYPE     string    `gorm:"column:FCTYPE;" json:"fctype"  form:"fctype" `
	FCU1ACC    string    `gorm:"column:FCU1ACC;" json:"fcu1acc"  form:"fcu1acc" `
	FCU1STATUS string    `gorm:"column:FCU1STATUS;" json:"fcu1status"  form:"fcu1status" `
	FCU2STATUS string    `gorm:"column:FCU2STATUS;" json:"fcu2status"  form:"fcu2status" `
	FCU3STATUS string    `gorm:"column:FCU3STATUS;" json:"fcu3status"  form:"fcu3status" `
	FCU4STATUS string    `gorm:"column:FCU4STATUS;" json:"fcu4status"  form:"fcu4status" `
	FCU5STATUS string    `gorm:"column:FCU5STATUS;" json:"fcu5status"  form:"fcu5status" `
	FCU6STATUS string    `gorm:"column:FCU6STATUS;" json:"fcu6status"  form:"fcu6status" `
	FCU7STATUS string    `gorm:"column:FCU7STATUS;" json:"fcu7status"  form:"fcu7status" `
	FCU8STATUS string    `gorm:"column:FCU8STATUS;" json:"fcu8status"  form:"fcu8status" `
	FCU9STATUS string    `gorm:"column:FCU9STATUS;" json:"fcu9status"  form:"fcu9status" `
	FCUSER01   string    `gorm:"column:FCUSER01;" json:"fcuser01"  form:"fcuser01" `
	FCUSER02   string    `gorm:"column:FCUSER02;" json:"fcuser02"  form:"fcuser02" `
	FCUSER03   string    `gorm:"column:FCUSER03;" json:"fcuser03"  form:"fcuser03" `
	FCWORKID   string    `gorm:"column:FCWORKID;" json:"fcworkid"  form:"fcworkid" `
	FCZIP      string    `gorm:"column:FCZIP;" json:"fczip"  form:"fczip" `
	FDADJSAL   string    `gorm:"column:FDADJSAL;" json:"fdadjsal"  form:"fdadjsal" `
	FDBIRTHDAT string    `gorm:"column:FDBIRTHDAT;" json:"fdbirthdat"  form:"fdbirthdat" `
	FDCBIRTHDA string    `gorm:"column:FDCBIRTHDA;" json:"fdcbirthda"  form:"fdcbirthda" `
	FDENDDRV1  string    `gorm:"column:FDENDDRV1;" json:"fdenddrv1"  form:"fdenddrv1" `
	FDENDDRV2  string    `gorm:"column:FDENDDRV2;" json:"fdenddrv2"  form:"fdenddrv2" `
	FDENDFOREI string    `gorm:"column:FDENDFOREI;" json:"fdendforei"  form:"fdendforei" `
	FDENDPASS  string    `gorm:"column:FDENDPASS;" json:"fdendpass"  form:"fdendpass" `
	FDENDWORK  string    `gorm:"column:FDENDWORK;" json:"fdendwork"  form:"fdendwork" `
	FDIDDATE   string    `gorm:"column:FDIDDATE;" json:"fdiddate"  form:"fdiddate" `
	FDIDEXPDAT string    `gorm:"column:FDIDEXPDAT;" json:"fdidexpdat"  form:"fdidexpdat" `
	FDQUITDATE string    `gorm:"column:FDQUITDATE;" json:"fdquitdate"  form:"fdquitdate" `
	FDRECRUIT  string    `gorm:"column:FDRECRUIT;" json:"fdrecruit"  form:"fdrecruit" `
	FDSTARTDAT string    `gorm:"column:FDSTARTDAT;" json:"fdstartdat"  form:"fdstartdat" `
	FIMILLISEC string    `gorm:"column:FIMILLISEC;" json:"fimillisec"  form:"fimillisec" `
	FMEXTRATAG string    `gorm:"column:FMEXTRATAG;" json:"fmextratag"  form:"fmextratag" `
	FMPICNAME  string    `gorm:"column:FMPICNAME;" json:"fmpicname"  form:"fmpicname" `
	FMREMARK   string    `gorm:"column:FMREMARK;" json:"fmremark"  form:"fmremark" `
	FMREMARK10 string    `gorm:"column:FMREMARK10;" json:"fmremark10"  form:"fmremark10" `
	FMREMARK2  string    `gorm:"column:FMREMARK2;" json:"fmremark2"  form:"fmremark2" `
	FMREMARK3  string    `gorm:"column:FMREMARK3;" json:"fmremark3"  form:"fmremark3" `
	FMREMARK4  string    `gorm:"column:FMREMARK4;" json:"fmremark4"  form:"fmremark4" `
	FMREMARK5  string    `gorm:"column:FMREMARK5;" json:"fmremark5"  form:"fmremark5" `
	FMREMARK6  string    `gorm:"column:FMREMARK6;" json:"fmremark6"  form:"fmremark6" `
	FMREMARK7  string    `gorm:"column:FMREMARK7;" json:"fmremark7"  form:"fmremark7" `
	FMREMARK8  string    `gorm:"column:FMREMARK8;" json:"fmremark8"  form:"fmremark8" `
	FMREMARK9  string    `gorm:"column:FMREMARK9;" json:"fmremark9"  form:"fmremark9" `
	FNBEGTIME1 string    `gorm:"column:FNBEGTIME1;" json:"fnbegtime1"  form:"fnbegtime1" `
	FNBEGTIME2 string    `gorm:"column:FNBEGTIME2;" json:"fnbegtime2"  form:"fnbegtime2" `
	FNBFFUND   string    `gorm:"column:FNBFFUND;" json:"fnbffund"  form:"fnbffund" `
	FNBFFUNDOV string    `gorm:"column:FNBFFUNDOV;" json:"fnbffundov"  form:"fnbffundov" `
	FNBFSALARY string    `gorm:"column:FNBFSALARY;" json:"fnbfsalary"  form:"fnbfsalary" `
	FNBFSOC    string    `gorm:"column:FNBFSOC;" json:"fnbfsoc"  form:"fnbfsoc" `
	FNBFTAX    string    `gorm:"column:FNBFTAX;" json:"fnbftax"  form:"fnbftax" `
	FNCFUND    string    `gorm:"column:FNCFUND;" json:"fncfund"  form:"fncfund" `
	FNCFUND2   string    `gorm:"column:FNCFUND2;" json:"fncfund2"  form:"fncfund2" `
	FNCFUNDOVR string    `gorm:"column:FNCFUNDOVR;" json:"fncfundovr"  form:"fncfundovr" `
	FNCINSURAM string    `gorm:"column:FNCINSURAM;" json:"fncinsuram"  form:"fncinsuram" `
	FNCLTFAMT  string    `gorm:"column:FNCLTFAMT;" json:"fncltfamt"  form:"fncltfamt" `
	FNCPVTEACH string    `gorm:"column:FNCPVTEACH;" json:"fncpvteach"  form:"fncpvteach" `
	FNCREPAY   string    `gorm:"column:FNCREPAY;" json:"fncrepay"  form:"fncrepay" `
	FNCRMFAMT  string    `gorm:"column:FNCRMFAMT;" json:"fncrmfamt"  form:"fncrmfamt" `
	FNCSALARY  string    `gorm:"column:FNCSALARY;" json:"fncsalary"  form:"fncsalary" `
	FNCSOCIAL  string    `gorm:"column:FNCSOCIAL;" json:"fncsocial"  form:"fncsocial" `
	FNDONATAMT string    `gorm:"column:FNDONATAMT;" json:"fndonatamt"  form:"fndonatamt" `
	FNENDTIME1 string    `gorm:"column:FNENDTIME1;" json:"fnendtime1"  form:"fnendtime1" `
	FNENDTIME2 string    `gorm:"column:FNENDTIME2;" json:"fnendtime2"  form:"fnendtime2" `
	FNFUND2    string    `gorm:"column:FNFUND2;" json:"fnfund2"  form:"fnfund2" `
	FNHEIGHT   string    `gorm:"column:FNHEIGHT;" json:"fnheight"  form:"fnheight" `
	FNINSURAMT string    `gorm:"column:FNINSURAMT;" json:"fninsuramt"  form:"fninsuramt" `
	FNLASTSAL  string    `gorm:"column:FNLASTSAL;" json:"fnlastsal"  form:"fnlastsal" `
	FNLENDAMT  string    `gorm:"column:FNLENDAMT;" json:"fnlendamt"  form:"fnlendamt" `
	FNLTFAMT   string    `gorm:"column:FNLTFAMT;" json:"fnltfamt"  form:"fnltfamt" `
	FNPAYOT    string    `gorm:"column:FNPAYOT;" json:"fnpayot"  form:"fnpayot" `
	FNPAYSPORT string    `gorm:"column:FNPAYSPORT;" json:"fnpaysport"  form:"fnpaysport" `
	FNPVTEACH  string    `gorm:"column:FNPVTEACH;" json:"fnpvteach"  form:"fnpvteach" `
	FNPYPERIOD string    `gorm:"column:FNPYPERIOD;" json:"fnpyperiod"  form:"fnpyperiod" `
	FNREPAY    string    `gorm:"column:FNREPAY;" json:"fnrepay"  form:"fnrepay" `
	FNRMFAMT   string    `gorm:"column:FNRMFAMT;" json:"fnrmfamt"  form:"fnrmfamt" `
	FNSALARY   string    `gorm:"column:FNSALARY;" json:"fnsalary"  form:"fnsalary" `
	FNSON      string    `gorm:"column:FNSON;" json:"fnson"  form:"fnson" `
	FNSONSCH   string    `gorm:"column:FNSONSCH;" json:"fnsonsch"  form:"fnsonsch" `
	FNSPAYLAST string    `gorm:"column:FNSPAYLAST;" json:"fnspaylast"  form:"fnspaylast" `
	FNSPEDUAMT string    `gorm:"column:FNSPEDUAMT;" json:"fnspeduamt"  form:"fnspeduamt" `
	FNU1CNT    string    `gorm:"column:FNU1CNT;" json:"fnu1cnt"  form:"fnu1cnt" `
	FNU2CNT    string    `gorm:"column:FNU2CNT;" json:"fnu2cnt"  form:"fnu2cnt" `
	FNU3CNT    string    `gorm:"column:FNU3CNT;" json:"fnu3cnt"  form:"fnu3cnt" `
	FNU4CNT    string    `gorm:"column:FNU4CNT;" json:"fnu4cnt"  form:"fnu4cnt" `
	FNU5CNT    string    `gorm:"column:FNU5CNT;" json:"fnu5cnt"  form:"fnu5cnt" `
	FNU6CNT    string    `gorm:"column:FNU6CNT;" json:"fnu6cnt"  form:"fnu6cnt" `
	FNU7CNT    string    `gorm:"column:FNU7CNT;" json:"fnu7cnt"  form:"fnu7cnt" `
	FNU8CNT    string    `gorm:"column:FNU8CNT;" json:"fnu8cnt"  form:"fnu8cnt" `
	FNU9CNT    string    `gorm:"column:FNU9CNT;" json:"fnu9cnt"  form:"fnu9cnt" `
	FNWEIGHT   string    `gorm:"column:FNWEIGHT;" json:"fnweight"  form:"fnweight" `
	FTDATETIME string    `gorm:"column:FTDATETIME;" json:"ftdatetime"  form:"ftdatetime" `
	FTLASTEDIT time.Time `gorm:"column:FTLASTEDIT;" json:"ftlastedit"  form:"ftlastedit" `
	FTLASTUPD  string    `gorm:"column:FTLASTUPD;" json:"ftlastupd"  form:"ftlastupd" `
	FTSRCUPD   string    `gorm:"column:FTSRCUPD;" json:"ftsrcupd"  form:"ftsrcupd" `
}

func (Emplx1) TableName() string {
	return "EMPLX1"
}

func (obj *Emplx1) BeforeCreate(tx *gorm.DB) (err error) {
	id, _ := g.New(6)
	obj.FCSKID = fmt.Sprintf("AB%s", id)
	return
}
